-- Generated by Oracle SQL Developer Data Modeler 4.0.2.840
--   at:        2017-02-14 11:45:53 BOT
--   site:      SQL Server 2008
--   type:      SQL Server 2008




ALTER TABLE Categoria
DROP
  CONSTRAINT Categoria_Categoria_FK
GO
ALTER TABLE Garantia
DROP
  CONSTRAINT Garantia_Categoria_FK
GO
ALTER TABLE Producto
DROP
  CONSTRAINT Producto_Categoria_FK
GO
DROP TABLE Categoria
GO

ALTER TABLE Compra_Producto
DROP
  CONSTRAINT Compra_Producto_Compra_FK
GO
DROP TABLE Compra
GO

DROP
  TABLE Compra_Producto
GO

ALTER TABLE Compra
DROP
  CONSTRAINT Compra_Direccion_FK
GO
ALTER TABLE Compra
DROP
  CONSTRAINT Compra_Direccion_FKv1
GO
DROP
  TABLE Direccion
GO

ALTER TABLE Compra
DROP
  CONSTRAINT Compra_Empresa_Envio_FK
GO
DROP
  TABLE Empresa_Envio
GO

ALTER TABLE Direccion
DROP
  CONSTRAINT Direccion_Estado_FK
GO
DROP TABLE Estado
GO

ALTER TABLE Compra
DROP
  CONSTRAINT Compra_Estatus_FK
GO
DROP TABLE Estatus
GO

DROP
  TABLE Garantia
GO

ALTER TABLE Usuario
DROP
  CONSTRAINT Usuario_Genero_FK
GO
DROP TABLE Genero
GO

DROP TABLE Imagen
GO

ALTER TABLE Garantia
DROP
  CONSTRAINT Garantia_Marca_FK
GO
ALTER TABLE Producto
DROP
  CONSTRAINT Producto_Marca_FK
GO
DROP TABLE Marca
GO

DROP
  TABLE Newsletter
GO

ALTER TABLE Compra
DROP
  CONSTRAINT Compra_Pago_FK
GO
DROP TABLE Pago
GO

ALTER TABLE Compra_Producto
DROP
  CONSTRAINT Compra_Producto_Producto_FK
GO
ALTER TABLE Imagen
DROP
  CONSTRAINT Imagen_Producto_FK
GO
ALTER TABLE Promocion
DROP
  CONSTRAINT Promocion_Producto_FK
GO
DROP
  TABLE Producto
GO

DROP
  TABLE Promocion
GO

ALTER TABLE Usuario
DROP
  CONSTRAINT Usuario_Rol_FK
GO
DROP TABLE Rol
GO

ALTER TABLE Compra
DROP
  CONSTRAINT Compra_Usuario_FK
GO
ALTER TABLE Direccion
DROP
  CONSTRAINT Direccion_Usuario_FK
GO
DROP TABLE Usuario
GO

CREATE
  TABLE Categoria
  (
    id     INTEGER IDENTITY NOT NULL ,
    Nombre VARCHAR (50) ,
    Activo INTEGER ,
    Destacado INTEGER ,
    Fecha_Creacion DATE ,
    Categoria_id   INTEGER ,
    CONSTRAINT Categoria_PK PRIMARY KEY CLUSTERED (id)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
  )
  ON "default"
GO

CREATE
  TABLE Compra
  (
    Id            INTEGER IDENTITY NOT NULL ,
    Pedido VARCHAR  (255) NOT NULL ,
    "Sub-Total" FLOAT ,
    IVA FLOAT ,
    Estatus_Id     INTEGER NOT NULL ,
    Usuario_Cedula INTEGER NOT NULL ,
    Usuario_Id     INTEGER NOT NULL ,
    Precio_Envio FLOAT ,
    Numero_Pedido    VARCHAR (50) ,
    Direccion_Id     INTEGER NOT NULL ,
    Direccion_Id1    INTEGER NOT NULL ,
    Pago_Id          INTEGER NOT NULL ,
    Empresa_Envio_Id INTEGER NOT NULL ,
    CONSTRAINT Compra_PK PRIMARY KEY CLUSTERED (id)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
  )
  ON "default"
GO

CREATE
  TABLE Compra_Producto
  (
    Fecha         DATE ,
    Producto_id   INTEGER NOT NULL ,
    Compra_Pedido VARCHAR (255) NOT NULL ,
    Precio FLOAT ,
    CONSTRAINT Compra_Producto_PK PRIMARY KEY CLUSTERED (Producto_id,
    Compra_Pedido)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
  )
  ON "default"
GO

CREATE
  TABLE Direccion
  (
    Id            INTEGER IDENTITY NOT NULL ,
    Ciudad        VARCHAR (255) ,
    Municipio     VARCHAR (255) ,
    Parroquia     VARCHAR (255) ,
    Zona          VARCHAR (255) ,
    Calle         VARCHAR (255) ,
    Edificio_Casa VARCHAR (255) ,
    Apartamento   VARCHAR (255) ,
    Estado_Id     INTEGER NOT NULL ,
    Usuario_Id    INTEGER NOT NULL ,
    CONSTRAINT Direccion_PK PRIMARY KEY CLUSTERED (Id)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
  )
  ON "default"
GO

CREATE
  TABLE Empresa_Envio
  (
    Id           INTEGER IDENTITY NOT NULL ,
    Nombre       VARCHAR (100) ,
    Tracking_url VARCHAR (255) ,
    Tiempo_Envio INTEGER ,
    CONSTRAINT Empresa_Envio_PK PRIMARY KEY CLUSTERED (Id)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
  )
  ON "default"
GO

CREATE
  TABLE Estado
  (
    Id     INTEGER IDENTITY NOT NULL ,
    Nombre VARCHAR (100) ,
    CONSTRAINT Estado_PK PRIMARY KEY CLUSTERED (Id)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
  )
  ON "default"
GO

CREATE
  TABLE Estatus
  (
    Id     INTEGER IDENTITY NOT NULL ,
    Estado VARCHAR (20) ,
    CONSTRAINT Estatus_PK PRIMARY KEY CLUSTERED (Id)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
  )
  ON "default"
GO

CREATE
  TABLE Garantia
  (
    id          INTEGER IDENTITY NOT NULL ,
    Duracion    VARCHAR (15) ,
    Condiciones VARCHAR (255) ,
    Marca_Id    INTEGER NOT NULL ,
    Activo INTEGER ,
    Categoria_id   INTEGER NOT NULL ,
    Fecha_Creacion DATE ,
    CONSTRAINT Garantia_PK PRIMARY KEY CLUSTERED (id)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
  )
  ON "default"
GO

CREATE
  TABLE Genero
  (
    id   INTEGER IDENTITY NOT NULL ,
    Sexo VARCHAR (10) ,
    CONSTRAINT Genero_PK PRIMARY KEY CLUSTERED (id)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
  )
  ON "default"
GO

CREATE
  TABLE Imagen
  (
    Id          INTEGER IDENTITY NOT NULL ,
    Producto_id INTEGER NOT NULL ,
    Ruta        VARCHAR (255) ,
    CONSTRAINT Imagen_PK PRIMARY KEY CLUSTERED (Id)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
  )
  ON "default"
GO

CREATE
  TABLE Marca
  (
    Id     INTEGER IDENTITY NOT NULL ,
    Nombre VARCHAR (50) ,
    Imagen VARCHAR (255) ,
    Activo INTEGER ,
    Fecha_Creacion DATE ,
    CONSTRAINT Marca_PK PRIMARY KEY CLUSTERED (Id)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
  )
  ON "default"
GO

CREATE
  TABLE Newsletter
  (
    id     INTEGER IDENTITY NOT NULL ,
    Correo VARCHAR ,
    Activo INTEGER ,
    CONSTRAINT Newsletter_PK PRIMARY KEY CLUSTERED (id)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
  )
  ON "default"
GO

CREATE
  TABLE Pago
  (
    Id INTEGER IDENTITY NOT NULL ,
    Monto FLOAT ,
    Numero_Referencia INTEGER ,
    Fecha_Registro    DATE ,
    Banco             VARCHAR (255) ,
    Tipo_pago         VARCHAR (100) ,
    Descripcion       VARCHAR (255) ,
    CONSTRAINT Pago_PK PRIMARY KEY CLUSTERED (Id)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
  )
  ON "default"
GO

CREATE
  TABLE Producto
  (
    SKU    INTEGER IDENTITY NOT NULL ,
    Nombre VARCHAR (50) ,
    Activo INTEGER ,
    Modelo      VARCHAR (50) ,
    Descripcion VARCHAR (255) ,
    Precio FLOAT ,
    cantidad INTEGER ,
    Peso FLOAT ,
    Alto FLOAT ,
    Ancho FLOAT ,
    Largo FLOAT ,
    Marca_Id           INTEGER NOT NULL ,
    Categoria_id       INTEGER NOT NULL ,
    Fecha_Creacion     DATE ,
    Fecha_Modificacion DATE ,
    CONSTRAINT Producto_PK PRIMARY KEY CLUSTERED (SKU)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
  )
  ON "default"
GO

CREATE
  TABLE Promocion
  (
    Id           INTEGER IDENTITY NOT NULL ,
    Producto_id  INTEGER NOT NULL ,
    Fecha_Inicio DATE ,
    Fecha_Fin    DATE ,
    Activo INTEGER ,
    Fecha_Creacion DATE ,
    Precio FLOAT ,
    CONSTRAINT Promocion_PK PRIMARY KEY CLUSTERED (Id)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
  )
  ON "default"
GO

CREATE
  TABLE Rol
  (
    Id     INTEGER IDENTITY NOT NULL ,
    Nombre VARCHAR (20) ,
    CONSTRAINT Rol_PK PRIMARY KEY CLUSTERED (Id)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
  )
  ON "default"
GO

CREATE
  TABLE Usuario
  (
    Nombre           VARCHAR (20) ,
    Apellido         VARCHAR (50) ,
    Cedula           VARCHAR (50)  NOT NULL ,
    Telefono         VARCHAR (50) ,
    Celular          VARCHAR (50) ,
    Password         VARCHAR (20) ,
    Fecha_Nacimineto DATE ,
    Fecha_Ingreso    DATE ,
    Email            VARCHAR (255) ,
    Genero_id        INTEGER NOT NULL ,
    Rol_Id           INTEGER  NOT NULL ,
    Id               INTEGER IDENTITY NOT NULL ,
    Tipo_documento VARCHAR (1) ,
    Origen         VARCHAR (20) ,
    Validacion_DC INTEGER ,
    Valido_DC INTEGER ,
    CONSTRAINT Usuario_PK PRIMARY KEY CLUSTERED (Id)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
  )
  ON "default"
GO

ALTER TABLE Categoria
ADD CONSTRAINT Categoria_Categoria_FK FOREIGN KEY
(
Categoria_id
)
REFERENCES Categoria
(
id
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Compra
ADD CONSTRAINT Compra_Direccion_FK FOREIGN KEY
(
Direccion_Id
)
REFERENCES Direccion
(
Id
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Compra
ADD CONSTRAINT Compra_Direccion_FKv1 FOREIGN KEY
(
Direccion_Id1
)
REFERENCES Direccion
(
Id
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Compra
ADD CONSTRAINT Compra_Empresa_Envio_FK FOREIGN KEY
(
Empresa_Envio_Id
)
REFERENCES Empresa_Envio
(
Id
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Compra
ADD CONSTRAINT Compra_Estatus_FK FOREIGN KEY
(
Estatus_Id
)
REFERENCES Estatus
(
Id
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Compra
ADD CONSTRAINT Compra_Pago_FK FOREIGN KEY
(
Pago_Id
)
REFERENCES Pago
(
Id
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Compra_Producto
ADD CONSTRAINT Compra_Producto_Compra_FK FOREIGN KEY
(
Compra_Pedido
)
REFERENCES Compra
(
Pedido
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Compra_Producto
ADD CONSTRAINT Compra_Producto_Producto_FK FOREIGN KEY
(
Producto_id
)
REFERENCES Producto
(
SKU
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Compra
ADD CONSTRAINT Compra_Usuario_FK FOREIGN KEY
(
Usuario_Id
)
REFERENCES Usuario
(
Id
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Direccion
ADD CONSTRAINT Direccion_Estado_FK FOREIGN KEY
(
Estado_Id
)
REFERENCES Estado
(
Id
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Direccion
ADD CONSTRAINT Direccion_Usuario_FK FOREIGN KEY
(
Usuario_Id
)
REFERENCES Usuario
(
Id
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Garantia
ADD CONSTRAINT Garantia_Categoria_FK FOREIGN KEY
(
Categoria_id
)
REFERENCES Categoria
(
id
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Garantia
ADD CONSTRAINT Garantia_Marca_FK FOREIGN KEY
(
Marca_Id
)
REFERENCES Marca
(
Id
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Imagen
ADD CONSTRAINT Imagen_Producto_FK FOREIGN KEY
(
Producto_id
)
REFERENCES Producto
(
SKU
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Producto
ADD CONSTRAINT Producto_Categoria_FK FOREIGN KEY
(
Categoria_id
)
REFERENCES Categoria
(
id
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Producto
ADD CONSTRAINT Producto_Marca_FK FOREIGN KEY
(
Marca_Id
)
REFERENCES Marca
(
Id
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Promocion
ADD CONSTRAINT Promocion_Producto_FK FOREIGN KEY
(
Producto_id
)
REFERENCES Producto
(
SKU
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Usuario
ADD CONSTRAINT Usuario_Genero_FK FOREIGN KEY
(
Genero_id
)
REFERENCES Genero
(
id
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Usuario
ADD CONSTRAINT Usuario_Rol_FK FOREIGN KEY
(
Rol_Id
)
REFERENCES Rol
(
Id
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO


-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            17
-- CREATE INDEX                             0
-- ALTER TABLE                             38
-- CREATE VIEW                              0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE DATABASE                          0
-- CREATE DEFAULT                           0
-- CREATE INDEX ON VIEW                     0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE ROLE                              0
-- CREATE RULE                              0
-- CREATE PARTITION FUNCTION                0
-- CREATE PARTITION SCHEME                  0
-- 
-- DROP DATABASE                            0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0


--Inserts
insert into Rol values('Administrador');
insert into Rol values('Operador');
insert into Rol values('Cliente');

insert into Genero values('Masculino');
insert into Genero values('Femenino'); 