//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatosCC.Producto {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursoProducto {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursoProducto() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DatosCC.Producto.RecursoProducto", typeof(RecursoProducto).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AgregarProducto.
        /// </summary>
        internal static string AddNuevoProducto {
            get {
                return ResourceManager.GetString("AddNuevoProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModificarProducto.
        /// </summary>
        internal static string ChangeProducto {
            get {
                return ResourceManager.GetString("ChangeProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConsultaProducto.
        /// </summary>
        internal static string ConsultProductos {
            get {
                return ResourceManager.GetString("ConsultProductos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConsultaProductoId.
        /// </summary>
        internal static string ConsultProductoXId {
            get {
                return ResourceManager.GetString("ConsultProductoXId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DesactivarProducto.
        /// </summary>
        internal static string DeactivateProducto {
            get {
                return ResourceManager.GetString("DeactivateProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Alto.
        /// </summary>
        internal static string ParamAlto {
            get {
                return ResourceManager.GetString("ParamAlto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @ancho.
        /// </summary>
        internal static string ParamAncho {
            get {
                return ResourceManager.GetString("ParamAncho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @cantidad.
        /// </summary>
        internal static string ParamCantidad {
            get {
                return ResourceManager.GetString("ParamCantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @descripcion.
        /// </summary>
        internal static string ParamDescripcion {
            get {
                return ResourceManager.GetString("ParamDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @fecha_creacion.
        /// </summary>
        internal static string ParamFechaCreacion {
            get {
                return ResourceManager.GetString("ParamFechaCreacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @fecha_mod.
        /// </summary>
        internal static string ParamFechaModificacion {
            get {
                return ResourceManager.GetString("ParamFechaModificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @id.
        /// </summary>
        internal static string ParamId {
            get {
                return ResourceManager.GetString("ParamId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @id_categoria.
        /// </summary>
        internal static string ParamIdCategoria {
            get {
                return ResourceManager.GetString("ParamIdCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @id_marca.
        /// </summary>
        internal static string ParamIdMarca {
            get {
                return ResourceManager.GetString("ParamIdMarca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @imagen.
        /// </summary>
        internal static string ParamImagen {
            get {
                return ResourceManager.GetString("ParamImagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @largo.
        /// </summary>
        internal static string Paramlargo {
            get {
                return ResourceManager.GetString("Paramlargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @modelo.
        /// </summary>
        internal static string ParamModelo {
            get {
                return ResourceManager.GetString("ParamModelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @nombre.
        /// </summary>
        internal static string ParamNombre {
            get {
                return ResourceManager.GetString("ParamNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @peso.
        /// </summary>
        internal static string ParamPeso {
            get {
                return ResourceManager.GetString("ParamPeso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @precio.
        /// </summary>
        internal static string ParamPrecio {
            get {
                return ResourceManager.GetString("ParamPrecio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @valido.
        /// </summary>
        internal static string Paramstatus {
            get {
                return ResourceManager.GetString("Paramstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activo.
        /// </summary>
        internal static string ProductoActivo {
            get {
                return ResourceManager.GetString("ProductoActivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alto.
        /// </summary>
        internal static string ProductoAlto {
            get {
                return ResourceManager.GetString("ProductoAlto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ancho.
        /// </summary>
        internal static string ProductoAncho {
            get {
                return ResourceManager.GetString("ProductoAncho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cantidad.
        /// </summary>
        internal static string ProductoCantidad {
            get {
                return ResourceManager.GetString("ProductoCantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripcion.
        /// </summary>
        internal static string ProductoDescripcion {
            get {
                return ResourceManager.GetString("ProductoDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha_Creacion.
        /// </summary>
        internal static string ProductoFechaCre {
            get {
                return ResourceManager.GetString("ProductoFechaCre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha_Modificacion.
        /// </summary>
        internal static string ProductoFechaMod {
            get {
                return ResourceManager.GetString("ProductoFechaMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria_id.
        /// </summary>
        internal static string ProductofKCategoria {
            get {
                return ResourceManager.GetString("ProductofKCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marca_Id.
        /// </summary>
        internal static string ProductoFkMARCA {
            get {
                return ResourceManager.GetString("ProductoFkMARCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKU.
        /// </summary>
        internal static string ProductoId {
            get {
                return ResourceManager.GetString("ProductoId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Largo.
        /// </summary>
        internal static string ProductoLargo {
            get {
                return ResourceManager.GetString("ProductoLargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modelo.
        /// </summary>
        internal static string ProductoModelo {
            get {
                return ResourceManager.GetString("ProductoModelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        internal static string ProductoNombre {
            get {
                return ResourceManager.GetString("ProductoNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peso.
        /// </summary>
        internal static string ProductoPeso {
            get {
                return ResourceManager.GetString("ProductoPeso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio.
        /// </summary>
        internal static string ProductoPrecio {
            get {
                return ResourceManager.GetString("ProductoPrecio", resourceCulture);
            }
        }
    }
}
