//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatosCC.Usuario {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursoUsuario {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursoUsuario() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DatosCC.Usuario.RecursoUsuario", typeof(RecursoUsuario).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AgregarUsuario.
        /// </summary>
        internal static string AddNuevoUsuario {
            get {
                return ResourceManager.GetString("AddNuevoUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModificarUsuario.
        /// </summary>
        internal static string ChangeUsuario {
            get {
                return ResourceManager.GetString("ChangeUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error BD.
        /// </summary>
        internal static string Codigo {
            get {
                return ResourceManager.GetString("Codigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConsultaUsuario.
        /// </summary>
        internal static string ConsultUsuario {
            get {
                return ResourceManager.GetString("ConsultUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConsultaUsuarioId.
        /// </summary>
        internal static string ConsultUsuarioXId {
            get {
                return ResourceManager.GetString("ConsultUsuarioXId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DesactivarUsuario.
        /// </summary>
        internal static string DeactivateUsuario {
            get {
                return ResourceManager.GetString("DeactivateUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error no reconocido.
        /// </summary>
        internal static string MensajeOtro {
            get {
                return ResourceManager.GetString("MensajeOtro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error de BD - .
        /// </summary>
        internal static string MensajeSQL {
            get {
                return ResourceManager.GetString("MensajeSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @apellido.
        /// </summary>
        internal static string ParamApellido {
            get {
                return ResourceManager.GetString("ParamApellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @cedula.
        /// </summary>
        internal static string ParamCedula {
            get {
                return ResourceManager.GetString("ParamCedula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @celular.
        /// </summary>
        internal static string ParamCelular {
            get {
                return ResourceManager.GetString("ParamCelular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @fecha_ingreso.
        /// </summary>
        internal static string ParamFechaIngreso {
            get {
                return ResourceManager.GetString("ParamFechaIngreso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @fecha_nac.
        /// </summary>
        internal static string ParamFechaNacimieto {
            get {
                return ResourceManager.GetString("ParamFechaNacimieto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @fk_genero.
        /// </summary>
        internal static string ParamGenero {
            get {
                return ResourceManager.GetString("ParamGenero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @id.
        /// </summary>
        internal static string ParamId {
            get {
                return ResourceManager.GetString("ParamId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @email.
        /// </summary>
        internal static string ParamMail {
            get {
                return ResourceManager.GetString("ParamMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @nombre.
        /// </summary>
        internal static string ParamNombre {
            get {
                return ResourceManager.GetString("ParamNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @origen.
        /// </summary>
        internal static string ParamOrigen {
            get {
                return ResourceManager.GetString("ParamOrigen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @password.
        /// </summary>
        internal static string ParamPassword {
            get {
                return ResourceManager.GetString("ParamPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @fk_rol.
        /// </summary>
        internal static string ParamRol {
            get {
                return ResourceManager.GetString("ParamRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @telefono.
        /// </summary>
        internal static string ParamTelefono {
            get {
                return ResourceManager.GetString("ParamTelefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @tipo_doc.
        /// </summary>
        internal static string ParamTipoDoc {
            get {
                return ResourceManager.GetString("ParamTipoDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @validacion_dc.
        /// </summary>
        internal static string ParamValidacionDC {
            get {
                return ResourceManager.GetString("ParamValidacionDC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @valido_dc.
        /// </summary>
        internal static string ParamValidoDC {
            get {
                return ResourceManager.GetString("ParamValidoDC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activo.
        /// </summary>
        internal static string ProductoActivo {
            get {
                return ResourceManager.GetString("ProductoActivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alto.
        /// </summary>
        internal static string ProductoAlto {
            get {
                return ResourceManager.GetString("ProductoAlto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ancho.
        /// </summary>
        internal static string ProductoAncho {
            get {
                return ResourceManager.GetString("ProductoAncho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cantidad.
        /// </summary>
        internal static string ProductoCantidad {
            get {
                return ResourceManager.GetString("ProductoCantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripcion.
        /// </summary>
        internal static string ProductoDescripcion {
            get {
                return ResourceManager.GetString("ProductoDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha_Creacion.
        /// </summary>
        internal static string ProductoFechaCre {
            get {
                return ResourceManager.GetString("ProductoFechaCre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha_Modificacion.
        /// </summary>
        internal static string ProductoFechaMod {
            get {
                return ResourceManager.GetString("ProductoFechaMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria_id.
        /// </summary>
        internal static string ProductofKCategoria {
            get {
                return ResourceManager.GetString("ProductofKCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marca_Id.
        /// </summary>
        internal static string ProductoFkMARCA {
            get {
                return ResourceManager.GetString("ProductoFkMARCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKU.
        /// </summary>
        internal static string ProductoId {
            get {
                return ResourceManager.GetString("ProductoId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Largo.
        /// </summary>
        internal static string ProductoLargo {
            get {
                return ResourceManager.GetString("ProductoLargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modelo.
        /// </summary>
        internal static string ProductoModelo {
            get {
                return ResourceManager.GetString("ProductoModelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        internal static string ProductoNombre {
            get {
                return ResourceManager.GetString("ProductoNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peso.
        /// </summary>
        internal static string ProductoPeso {
            get {
                return ResourceManager.GetString("ProductoPeso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio.
        /// </summary>
        internal static string ProductoPrecio {
            get {
                return ResourceManager.GetString("ProductoPrecio", resourceCulture);
            }
        }
    }
}
