//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatosCC.Garantia {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursoGarantia {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursoGarantia() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DatosCC.Garantia.RecursoGarantia", typeof(RecursoGarantia).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AgregarGarantia.
        /// </summary>
        internal static string AddNuevaGarantia {
            get {
                return ResourceManager.GetString("AddNuevaGarantia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModificarGarantia.
        /// </summary>
        internal static string ChangeGarantia {
            get {
                return ResourceManager.GetString("ChangeGarantia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error BD.
        /// </summary>
        internal static string Codigo {
            get {
                return ResourceManager.GetString("Codigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TGE_00_001.
        /// </summary>
        internal static string Codigo_Error_Formato {
            get {
                return ResourceManager.GetString("Codigo_Error_Formato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to com_acronimo.
        /// </summary>
        internal static string ComAcronymCompany {
            get {
                return ResourceManager.GetString("ComAcronymCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to com_presupuesto.
        /// </summary>
        internal static string ComBudgetCompany {
            get {
                return ResourceManager.GetString("ComBudgetCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to com_plazo_pago.
        /// </summary>
        internal static string ComDeadlineCompany {
            get {
                return ResourceManager.GetString("ComDeadlineCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to com_email.
        /// </summary>
        internal static string ComEmailCompany {
            get {
                return ResourceManager.GetString("ComEmailCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to com_id.
        /// </summary>
        internal static string ComIdCompany {
            get {
                return ResourceManager.GetString("ComIdCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fk_lug_dir_id.
        /// </summary>
        internal static string ComIdPlace {
            get {
                return ResourceManager.GetString("ComIdPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to com_nombre.
        /// </summary>
        internal static string ComNameCompany {
            get {
                return ResourceManager.GetString("ComNameCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to com_fecha_registro.
        /// </summary>
        internal static string ComRegisterDateCompany {
            get {
                return ResourceManager.GetString("ComRegisterDateCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to com_rif.
        /// </summary>
        internal static string ComRifCompany {
            get {
                return ResourceManager.GetString("ComRifCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to com_status.
        /// </summary>
        internal static string ComStatusCompany {
            get {
                return ResourceManager.GetString("ComStatusCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to com_telefono.
        /// </summary>
        internal static string ComTelephoneCompany {
            get {
                return ResourceManager.GetString("ComTelephoneCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M4_ConsultarCompanias.
        /// </summary>
        internal static string ConsultCompanies {
            get {
                return ResourceManager.GetString("ConsultCompanies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M4_ConsultarCompania.
        /// </summary>
        internal static string ConsultCompany {
            get {
                return ResourceManager.GetString("ConsultCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M4_ConsultarCompaniasActivas.
        /// </summary>
        internal static string ConsultEnableCompanies {
            get {
                return ResourceManager.GetString("ConsultEnableCompanies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConsultarGarantia.
        /// </summary>
        internal static string ConsultGarantia {
            get {
                return ResourceManager.GetString("ConsultGarantia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConsultaGarantiaId.
        /// </summary>
        internal static string ConsultGarantiaXId {
            get {
                return ResourceManager.GetString("ConsultGarantiaXId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M4_ConsultarIdUltimaCompania.
        /// </summary>
        internal static string ConsultLastCompanyId {
            get {
                return ResourceManager.GetString("ConsultLastCompanyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DesactivarCategoria.
        /// </summary>
        internal static string DeactivateCate {
            get {
                return ResourceManager.GetString("DeactivateCate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M4_InhabilitarHabilitarCompania.
        /// </summary>
        internal static string DisableAbleComany {
            get {
                return ResourceManager.GetString("DisableAbleComany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria.
        /// </summary>
        internal static string GarantiaCategoria {
            get {
                return ResourceManager.GetString("GarantiaCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condiciones.
        /// </summary>
        internal static string GarantiaCondiciones {
            get {
                return ResourceManager.GetString("GarantiaCondiciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha_Creacion.
        /// </summary>
        internal static string GarantiaFechaCre {
            get {
                return ResourceManager.GetString("GarantiaFechaCre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria_id.
        /// </summary>
        internal static string GarantiafKCategoria {
            get {
                return ResourceManager.GetString("GarantiafKCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id.
        /// </summary>
        internal static string GarantiaId {
            get {
                return ResourceManager.GetString("GarantiaId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marca.
        /// </summary>
        internal static string GarantiaMarca {
            get {
                return ResourceManager.GetString("GarantiaMarca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error de parseo.
        /// </summary>
        internal static string Mensaje_Error_Formato {
            get {
                return ResourceManager.GetString("Mensaje_Error_Formato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salida del Método.
        /// </summary>
        internal static string MensajeFinInfoLogger {
            get {
                return ResourceManager.GetString("MensajeFinInfoLogger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error de formato - .
        /// </summary>
        internal static string MensajeFormato {
            get {
                return ResourceManager.GetString("MensajeFormato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrada en el Método.
        /// </summary>
        internal static string MensajeInicioInfoLogger {
            get {
                return ResourceManager.GetString("MensajeInicioInfoLogger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error por nulo - .
        /// </summary>
        internal static string MensajeNull {
            get {
                return ResourceManager.GetString("MensajeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error no reconocido.
        /// </summary>
        internal static string MensajeOtro {
            get {
                return ResourceManager.GetString("MensajeOtro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error de BD - .
        /// </summary>
        internal static string MensajeSQL {
            get {
                return ResourceManager.GetString("MensajeSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @apellido.
        /// </summary>
        internal static string ParamApellido {
            get {
                return ResourceManager.GetString("ParamApellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @fk_categoria.
        /// </summary>
        internal static string ParamCategoria {
            get {
                return ResourceManager.GetString("ParamCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @condiciones.
        /// </summary>
        internal static string ParamCondiciones {
            get {
                return ResourceManager.GetString("ParamCondiciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @email.
        /// </summary>
        internal static string ParamEmail {
            get {
                return ResourceManager.GetString("ParamEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @fecha_creacion.
        /// </summary>
        internal static string ParamFechaCreacion {
            get {
                return ResourceManager.GetString("ParamFechaCreacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @id_garantia.
        /// </summary>
        internal static string ParamId {
            get {
                return ResourceManager.GetString("ParamId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @id_lugar.
        /// </summary>
        internal static string ParamIdLugar {
            get {
                return ResourceManager.GetString("ParamIdLugar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @imagen.
        /// </summary>
        internal static string ParamImagen {
            get {
                return ResourceManager.GetString("ParamImagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @fk_marca.
        /// </summary>
        internal static string ParamMarca {
            get {
                return ResourceManager.GetString("ParamMarca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @plazo_pago.
        /// </summary>
        internal static string ParamPlazoPago {
            get {
                return ResourceManager.GetString("ParamPlazoPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @presupuesto.
        /// </summary>
        internal static string ParamPresupuesto {
            get {
                return ResourceManager.GetString("ParamPresupuesto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @rif.
        /// </summary>
        internal static string ParamRif {
            get {
                return ResourceManager.GetString("ParamRif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @telefono.
        /// </summary>
        internal static string ParamTelefono {
            get {
                return ResourceManager.GetString("ParamTelefono", resourceCulture);
            }
        }
    }
}
