//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatosCC.Marca {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursoMarca {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursoMarca() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DatosCC.Marca.RecursoMarca", typeof(RecursoMarca).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AgregarMarca.
        /// </summary>
        internal static string AddNuevaMarca {
            get {
                return ResourceManager.GetString("AddNuevaMarca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModificarMarca.
        /// </summary>
        internal static string ChangeMarca {
            get {
                return ResourceManager.GetString("ChangeMarca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error BD.
        /// </summary>
        internal static string Codigo {
            get {
                return ResourceManager.GetString("Codigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TGE_00_001.
        /// </summary>
        internal static string Codigo_Error_Formato {
            get {
                return ResourceManager.GetString("Codigo_Error_Formato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConsultarMarca.
        /// </summary>
        internal static string ConsultMarcas {
            get {
                return ResourceManager.GetString("ConsultMarcas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConsultaMarcaId.
        /// </summary>
        internal static string ConsultMarcaXId {
            get {
                return ResourceManager.GetString("ConsultMarcaXId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DesactivarMarca.
        /// </summary>
        internal static string DeactivateMarca {
            get {
                return ResourceManager.GetString("DeactivateMarca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activo.
        /// </summary>
        internal static string MarcaActivo {
            get {
                return ResourceManager.GetString("MarcaActivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cantidad.
        /// </summary>
        internal static string MarcaCantidad {
            get {
                return ResourceManager.GetString("MarcaCantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha_Creacion.
        /// </summary>
        internal static string MarcaFechaCre {
            get {
                return ResourceManager.GetString("MarcaFechaCre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha_Modificacion.
        /// </summary>
        internal static string MarcaFechaMod {
            get {
                return ResourceManager.GetString("MarcaFechaMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria_id.
        /// </summary>
        internal static string MarcafKCategoria {
            get {
                return ResourceManager.GetString("MarcafKCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marca_Id.
        /// </summary>
        internal static string MarcaFkMARCA {
            get {
                return ResourceManager.GetString("MarcaFkMARCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id.
        /// </summary>
        internal static string MarcaId {
            get {
                return ResourceManager.GetString("MarcaId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imagen.
        /// </summary>
        internal static string MarcaImagen {
            get {
                return ResourceManager.GetString("MarcaImagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modelo.
        /// </summary>
        internal static string MarcaModelo {
            get {
                return ResourceManager.GetString("MarcaModelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        internal static string MarcaNombre {
            get {
                return ResourceManager.GetString("MarcaNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peso.
        /// </summary>
        internal static string MarcaPeso {
            get {
                return ResourceManager.GetString("MarcaPeso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio.
        /// </summary>
        internal static string MarcaPrecio {
            get {
                return ResourceManager.GetString("MarcaPrecio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error de parseo.
        /// </summary>
        internal static string Mensaje_Error_Formato {
            get {
                return ResourceManager.GetString("Mensaje_Error_Formato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salida del Método.
        /// </summary>
        internal static string MensajeFinInfoLogger {
            get {
                return ResourceManager.GetString("MensajeFinInfoLogger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error de formato - .
        /// </summary>
        internal static string MensajeFormato {
            get {
                return ResourceManager.GetString("MensajeFormato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrada en el Método.
        /// </summary>
        internal static string MensajeInicioInfoLogger {
            get {
                return ResourceManager.GetString("MensajeInicioInfoLogger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error por nulo - .
        /// </summary>
        internal static string MensajeNull {
            get {
                return ResourceManager.GetString("MensajeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error no reconocido.
        /// </summary>
        internal static string MensajeOtro {
            get {
                return ResourceManager.GetString("MensajeOtro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error de BD - .
        /// </summary>
        internal static string MensajeSQL {
            get {
                return ResourceManager.GetString("MensajeSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @email.
        /// </summary>
        internal static string ParamEmail {
            get {
                return ResourceManager.GetString("ParamEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @fecha_creacion.
        /// </summary>
        internal static string ParamFechaCreacion {
            get {
                return ResourceManager.GetString("ParamFechaCreacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @id.
        /// </summary>
        internal static string ParamId {
            get {
                return ResourceManager.GetString("ParamId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @id_lugar.
        /// </summary>
        internal static string ParamIdLugar {
            get {
                return ResourceManager.GetString("ParamIdLugar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @imagen.
        /// </summary>
        internal static string ParamImagen {
            get {
                return ResourceManager.GetString("ParamImagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @nombre.
        /// </summary>
        internal static string ParamNombre {
            get {
                return ResourceManager.GetString("ParamNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @plazo_pago.
        /// </summary>
        internal static string ParamPlazoPago {
            get {
                return ResourceManager.GetString("ParamPlazoPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @presupuesto.
        /// </summary>
        internal static string ParamPresupuesto {
            get {
                return ResourceManager.GetString("ParamPresupuesto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @rif.
        /// </summary>
        internal static string ParamRif {
            get {
                return ResourceManager.GetString("ParamRif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @activo.
        /// </summary>
        internal static string ParamStatus {
            get {
                return ResourceManager.GetString("ParamStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @telefono.
        /// </summary>
        internal static string ParamTelefono {
            get {
                return ResourceManager.GetString("ParamTelefono", resourceCulture);
            }
        }
    }
}
