//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatosCC.Categoria {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursoCategoria {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursoCategoria() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DatosCC.Categoria.RecursoCategoria", typeof(RecursoCategoria).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AgregarCategoria.
        /// </summary>
        internal static string AddNuevaCategoria {
            get {
                return ResourceManager.GetString("AddNuevaCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activo.
        /// </summary>
        internal static string CategoriaActivo {
            get {
                return ResourceManager.GetString("CategoriaActivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destacado.
        /// </summary>
        internal static string CategoriaDestacado {
            get {
                return ResourceManager.GetString("CategoriaDestacado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha_Creacion.
        /// </summary>
        internal static string CategoriaFechaCre {
            get {
                return ResourceManager.GetString("CategoriaFechaCre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria_id.
        /// </summary>
        internal static string CategoriafKCategoria {
            get {
                return ResourceManager.GetString("CategoriafKCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id.
        /// </summary>
        internal static string CategoriaId {
            get {
                return ResourceManager.GetString("CategoriaId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        internal static string CategoriaNombre {
            get {
                return ResourceManager.GetString("CategoriaNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModificarCategoria.
        /// </summary>
        internal static string ChangeCategoria {
            get {
                return ResourceManager.GetString("ChangeCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error BD.
        /// </summary>
        internal static string Codigo {
            get {
                return ResourceManager.GetString("Codigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TGE_00_001.
        /// </summary>
        internal static string Codigo_Error_Formato {
            get {
                return ResourceManager.GetString("Codigo_Error_Formato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to com_acronimo.
        /// </summary>
        internal static string ComAcronymCompany {
            get {
                return ResourceManager.GetString("ComAcronymCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to com_presupuesto.
        /// </summary>
        internal static string ComBudgetCompany {
            get {
                return ResourceManager.GetString("ComBudgetCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to com_plazo_pago.
        /// </summary>
        internal static string ComDeadlineCompany {
            get {
                return ResourceManager.GetString("ComDeadlineCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to com_email.
        /// </summary>
        internal static string ComEmailCompany {
            get {
                return ResourceManager.GetString("ComEmailCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to com_id.
        /// </summary>
        internal static string ComIdCompany {
            get {
                return ResourceManager.GetString("ComIdCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fk_lug_dir_id.
        /// </summary>
        internal static string ComIdPlace {
            get {
                return ResourceManager.GetString("ComIdPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to com_nombre.
        /// </summary>
        internal static string ComNameCompany {
            get {
                return ResourceManager.GetString("ComNameCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to com_fecha_registro.
        /// </summary>
        internal static string ComRegisterDateCompany {
            get {
                return ResourceManager.GetString("ComRegisterDateCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to com_rif.
        /// </summary>
        internal static string ComRifCompany {
            get {
                return ResourceManager.GetString("ComRifCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to com_status.
        /// </summary>
        internal static string ComStatusCompany {
            get {
                return ResourceManager.GetString("ComStatusCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to com_telefono.
        /// </summary>
        internal static string ComTelephoneCompany {
            get {
                return ResourceManager.GetString("ComTelephoneCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConsultaCategoria.
        /// </summary>
        internal static string ConsultCategorias {
            get {
                return ResourceManager.GetString("ConsultCategorias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConsultaCategoriaId.
        /// </summary>
        internal static string ConsultCategoriaXId {
            get {
                return ResourceManager.GetString("ConsultCategoriaXId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M4_ConsultarCompanias.
        /// </summary>
        internal static string ConsultCompanies {
            get {
                return ResourceManager.GetString("ConsultCompanies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M4_ConsultarCompania.
        /// </summary>
        internal static string ConsultCompany {
            get {
                return ResourceManager.GetString("ConsultCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M4_ConsultarCompaniasActivas.
        /// </summary>
        internal static string ConsultEnableCompanies {
            get {
                return ResourceManager.GetString("ConsultEnableCompanies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M4_ConsultarIdUltimaCompania.
        /// </summary>
        internal static string ConsultLastCompanyId {
            get {
                return ResourceManager.GetString("ConsultLastCompanyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DesactivarCategoria.
        /// </summary>
        internal static string DeactivateCate {
            get {
                return ResourceManager.GetString("DeactivateCate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M4_InhabilitarHabilitarCompania.
        /// </summary>
        internal static string DisableAbleComany {
            get {
                return ResourceManager.GetString("DisableAbleComany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error de parseo.
        /// </summary>
        internal static string Mensaje_Error_Formato {
            get {
                return ResourceManager.GetString("Mensaje_Error_Formato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salida del Método.
        /// </summary>
        internal static string MensajeFinInfoLogger {
            get {
                return ResourceManager.GetString("MensajeFinInfoLogger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrada en el Método.
        /// </summary>
        internal static string MensajeInicioInfoLogger {
            get {
                return ResourceManager.GetString("MensajeInicioInfoLogger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error no reconocido.
        /// </summary>
        internal static string MensajeOtro {
            get {
                return ResourceManager.GetString("MensajeOtro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error de BD - .
        /// </summary>
        internal static string MensajeSQL {
            get {
                return ResourceManager.GetString("MensajeSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @apellido.
        /// </summary>
        internal static string ParamApellido {
            get {
                return ResourceManager.GetString("ParamApellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @destacado.
        /// </summary>
        internal static string ParamDestacado {
            get {
                return ResourceManager.GetString("ParamDestacado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @email.
        /// </summary>
        internal static string ParamEmail {
            get {
                return ResourceManager.GetString("ParamEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @fecha_creacion.
        /// </summary>
        internal static string ParamFechaCreacion {
            get {
                return ResourceManager.GetString("ParamFechaCreacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @id.
        /// </summary>
        internal static string ParamId {
            get {
                return ResourceManager.GetString("ParamId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @id_lugar.
        /// </summary>
        internal static string ParamIdLugar {
            get {
                return ResourceManager.GetString("ParamIdLugar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @imagen.
        /// </summary>
        internal static string ParamImagen {
            get {
                return ResourceManager.GetString("ParamImagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @nombre.
        /// </summary>
        internal static string ParamNombre {
            get {
                return ResourceManager.GetString("ParamNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @plazo_pago.
        /// </summary>
        internal static string ParamPlazoPago {
            get {
                return ResourceManager.GetString("ParamPlazoPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @presupuesto.
        /// </summary>
        internal static string ParamPresupuesto {
            get {
                return ResourceManager.GetString("ParamPresupuesto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @rif.
        /// </summary>
        internal static string ParamRif {
            get {
                return ResourceManager.GetString("ParamRif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @activo.
        /// </summary>
        internal static string ParamStatus {
            get {
                return ResourceManager.GetString("ParamStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @telefono.
        /// </summary>
        internal static string ParamTelefono {
            get {
                return ResourceManager.GetString("ParamTelefono", resourceCulture);
            }
        }
    }
}
