//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatosCC.Venta {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursoVenta {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursoVenta() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DatosCC.Venta.RecursoVenta", typeof(RecursoVenta).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AgregarUsuario.
        /// </summary>
        internal static string AddNuevoUsuario {
            get {
                return ResourceManager.GetString("AddNuevoUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModificarVenta.
        /// </summary>
        internal static string ChangeVenta {
            get {
                return ResourceManager.GetString("ChangeVenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error BD.
        /// </summary>
        internal static string Codigo {
            get {
                return ResourceManager.GetString("Codigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConsultaUsuarioId.
        /// </summary>
        internal static string ConsultUsuarioXId {
            get {
                return ResourceManager.GetString("ConsultUsuarioXId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConsultaVenta.
        /// </summary>
        internal static string ConsultVenta {
            get {
                return ResourceManager.GetString("ConsultVenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DesactivarUsuario.
        /// </summary>
        internal static string DeactivateUsuario {
            get {
                return ResourceManager.GetString("DeactivateUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error no reconocido.
        /// </summary>
        internal static string MensajeOtro {
            get {
                return ResourceManager.GetString("MensajeOtro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error de BD - .
        /// </summary>
        internal static string MensajeSQL {
            get {
                return ResourceManager.GetString("MensajeSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @apellido.
        /// </summary>
        internal static string ParamApellido {
            get {
                return ResourceManager.GetString("ParamApellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @cedula.
        /// </summary>
        internal static string ParamCedula {
            get {
                return ResourceManager.GetString("ParamCedula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @celular.
        /// </summary>
        internal static string ParamCelular {
            get {
                return ResourceManager.GetString("ParamCelular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @fecha_ingreso.
        /// </summary>
        internal static string ParamFechaIngreso {
            get {
                return ResourceManager.GetString("ParamFechaIngreso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @fecha_nac.
        /// </summary>
        internal static string ParamFechaNacimieto {
            get {
                return ResourceManager.GetString("ParamFechaNacimieto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @fk_genero.
        /// </summary>
        internal static string ParamGenero {
            get {
                return ResourceManager.GetString("ParamGenero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @idVenta.
        /// </summary>
        internal static string ParamId {
            get {
                return ResourceManager.GetString("ParamId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @nombre.
        /// </summary>
        internal static string ParamNombre {
            get {
                return ResourceManager.GetString("ParamNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @origen.
        /// </summary>
        internal static string ParamOrigen {
            get {
                return ResourceManager.GetString("ParamOrigen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @password.
        /// </summary>
        internal static string ParamPassword {
            get {
                return ResourceManager.GetString("ParamPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @fk_rol.
        /// </summary>
        internal static string ParamRol {
            get {
                return ResourceManager.GetString("ParamRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @estatus.
        /// </summary>
        internal static string ParamStatus {
            get {
                return ResourceManager.GetString("ParamStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @telefono.
        /// </summary>
        internal static string ParamTelefono {
            get {
                return ResourceManager.GetString("ParamTelefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @tipo_doc.
        /// </summary>
        internal static string ParamTipoDoc {
            get {
                return ResourceManager.GetString("ParamTipoDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @validacion_dc.
        /// </summary>
        internal static string ParamValidacionDC {
            get {
                return ResourceManager.GetString("ParamValidacionDC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @valido_dc.
        /// </summary>
        internal static string ParamValidoDC {
            get {
                return ResourceManager.GetString("ParamValidoDC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to apeusu.
        /// </summary>
        internal static string VentaApellido {
            get {
                return ResourceManager.GetString("VentaApellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to correo.
        /// </summary>
        internal static string VentaCorreo {
            get {
                return ResourceManager.GetString("VentaCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DirEnvio.
        /// </summary>
        internal static string VentaDirEnv {
            get {
                return ResourceManager.GetString("VentaDirEnv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirfacturacion.
        /// </summary>
        internal static string VentaDirFact {
            get {
                return ResourceManager.GetString("VentaDirFact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to estatus.
        /// </summary>
        internal static string VentaEstatus {
            get {
                return ResourceManager.GetString("VentaEstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        internal static string ventaFecha {
            get {
                return ResourceManager.GetString("ventaFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idventa.
        /// </summary>
        internal static string VentaId {
            get {
                return ResourceManager.GetString("VentaId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iva.
        /// </summary>
        internal static string VentaIva {
            get {
                return ResourceManager.GetString("VentaIva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marca.
        /// </summary>
        internal static string VentaMarca {
            get {
                return ResourceManager.GetString("VentaMarca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modelo.
        /// </summary>
        internal static string VentaModelo {
            get {
                return ResourceManager.GetString("VentaModelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nombreusu.
        /// </summary>
        internal static string VentaNombre {
            get {
                return ResourceManager.GetString("VentaNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to numpago.
        /// </summary>
        internal static string VentaNPago {
            get {
                return ResourceManager.GetString("VentaNPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to operador.
        /// </summary>
        internal static string VentaOperador {
            get {
                return ResourceManager.GetString("VentaOperador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to numpedido.
        /// </summary>
        internal static string VentaPedido {
            get {
                return ResourceManager.GetString("VentaPedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        internal static string VentaProducto {
            get {
                return ResourceManager.GetString("VentaProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to precioenv.
        /// </summary>
        internal static string VentasPEnvio {
            get {
                return ResourceManager.GetString("VentasPEnvio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subtotal.
        /// </summary>
        internal static string ventaSub {
            get {
                return ResourceManager.GetString("ventaSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to track.
        /// </summary>
        internal static string VentaTracking {
            get {
                return ResourceManager.GetString("VentaTracking", resourceCulture);
            }
        }
    }
}
