//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatosCC.Promocion {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursoPromocion {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursoPromocion() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DatosCC.Promocion.RecursoPromocion", typeof(RecursoPromocion).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AgregarPromocion.
        /// </summary>
        internal static string AddNuevaPromocion {
            get {
                return ResourceManager.GetString("AddNuevaPromocion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModificarPromocion.
        /// </summary>
        internal static string Changepromo {
            get {
                return ResourceManager.GetString("Changepromo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error BD.
        /// </summary>
        internal static string Codigo {
            get {
                return ResourceManager.GetString("Codigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TGE_00_001.
        /// </summary>
        internal static string Codigo_Error_Formato {
            get {
                return ResourceManager.GetString("Codigo_Error_Formato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConsultaMarcaId.
        /// </summary>
        internal static string ConsultMarcaXId {
            get {
                return ResourceManager.GetString("ConsultMarcaXId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConsultarPromociones.
        /// </summary>
        internal static string ConsultPromos {
            get {
                return ResourceManager.GetString("ConsultPromos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DesactivarPromocion.
        /// </summary>
        internal static string Deactivate {
            get {
                return ResourceManager.GetString("Deactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha_Fin.
        /// </summary>
        internal static string FechaFin {
            get {
                return ResourceManager.GetString("FechaFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha_Inicio.
        /// </summary>
        internal static string FechaIni {
            get {
                return ResourceManager.GetString("FechaIni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cantidad.
        /// </summary>
        internal static string MarcaCantidad {
            get {
                return ResourceManager.GetString("MarcaCantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha_Modificacion.
        /// </summary>
        internal static string MarcaFechaMod {
            get {
                return ResourceManager.GetString("MarcaFechaMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria_id.
        /// </summary>
        internal static string MarcafKCategoria {
            get {
                return ResourceManager.GetString("MarcafKCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marca_Id.
        /// </summary>
        internal static string MarcaFkMARCA {
            get {
                return ResourceManager.GetString("MarcaFkMARCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peso.
        /// </summary>
        internal static string MarcaPeso {
            get {
                return ResourceManager.GetString("MarcaPeso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error de parseo.
        /// </summary>
        internal static string Mensaje_Error_Formato {
            get {
                return ResourceManager.GetString("Mensaje_Error_Formato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salida del Método.
        /// </summary>
        internal static string MensajeFinInfoLogger {
            get {
                return ResourceManager.GetString("MensajeFinInfoLogger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error de formato - .
        /// </summary>
        internal static string MensajeFormato {
            get {
                return ResourceManager.GetString("MensajeFormato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrada en el Método.
        /// </summary>
        internal static string MensajeInicioInfoLogger {
            get {
                return ResourceManager.GetString("MensajeInicioInfoLogger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error por nulo - .
        /// </summary>
        internal static string MensajeNull {
            get {
                return ResourceManager.GetString("MensajeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error no reconocido.
        /// </summary>
        internal static string MensajeOtro {
            get {
                return ResourceManager.GetString("MensajeOtro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error de BD - .
        /// </summary>
        internal static string MensajeSQL {
            get {
                return ResourceManager.GetString("MensajeSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @email.
        /// </summary>
        internal static string ParamEmail {
            get {
                return ResourceManager.GetString("ParamEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @fecha_creacion.
        /// </summary>
        internal static string ParamFechaCreacion {
            get {
                return ResourceManager.GetString("ParamFechaCreacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @fecha_fin.
        /// </summary>
        internal static string ParamFechaFin {
            get {
                return ResourceManager.GetString("ParamFechaFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @fecha_inicio.
        /// </summary>
        internal static string ParamFechaInicio {
            get {
                return ResourceManager.GetString("ParamFechaInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @id_promocion.
        /// </summary>
        internal static string ParamId {
            get {
                return ResourceManager.GetString("ParamId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @id_lugar.
        /// </summary>
        internal static string ParamIdLugar {
            get {
                return ResourceManager.GetString("ParamIdLugar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @plazo_pago.
        /// </summary>
        internal static string ParamPlazoPago {
            get {
                return ResourceManager.GetString("ParamPlazoPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @precio.
        /// </summary>
        internal static string ParamPrecio {
            get {
                return ResourceManager.GetString("ParamPrecio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @presupuesto.
        /// </summary>
        internal static string ParamPresupuesto {
            get {
                return ResourceManager.GetString("ParamPresupuesto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @producto.
        /// </summary>
        internal static string ParamProducto {
            get {
                return ResourceManager.GetString("ParamProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @rif.
        /// </summary>
        internal static string ParamRif {
            get {
                return ResourceManager.GetString("ParamRif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @activo.
        /// </summary>
        internal static string ParamStatus {
            get {
                return ResourceManager.GetString("ParamStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @telefono.
        /// </summary>
        internal static string ParamTelefono {
            get {
                return ResourceManager.GetString("ParamTelefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Producto_id.
        /// </summary>
        internal static string ProductoID {
            get {
                return ResourceManager.GetString("ProductoID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activo.
        /// </summary>
        internal static string PromoActivo {
            get {
                return ResourceManager.GetString("PromoActivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha_Creacion.
        /// </summary>
        internal static string PromoFechaCre {
            get {
                return ResourceManager.GetString("PromoFechaCre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promo_id.
        /// </summary>
        internal static string PromoId {
            get {
                return ResourceManager.GetString("PromoId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio.
        /// </summary>
        internal static string PromoPrecio {
            get {
                return ResourceManager.GetString("PromoPrecio", resourceCulture);
            }
        }
    }
}
